name: ld38
description: A ld38 game
dependencies:
  browser: any
  dartemis:
    path: ../dartemis
  dartemis_transformer: 
    path: ../dartemis_transformer
  gamedev_helpers:
#    git: https://github.com/denniskaselow/gamedev_helpers
    path: ../gamedev_helpers
  dart_to_js_script_rewriter: any
  a_star: ^0.3.0
transformers:
- dart_to_js_script_rewriter
- dartemis_transformer:
    additionalLibraries:
    - gamedev_helpers/gamedev_helpers.dart
